// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_list_header: dynamic(() => import("./BlogListHeader")),
  blog_posts_list: dynamic(() => import("./BlogPostsList")),
  rich_text: dynamic(() => import("./RichText")),
};
